Levels:
  StartingLevelName: ""
Docking:
  DockFloatingWindows: false
  DockPadding: [10, 10]
Console:
  LogColor: [1, 0.999989986, 0.999989986, 1]
  WarningColor: [1, 1, 0, 1]
  ErrorColor: [1, 0, 0, 1]
EditorCamera:
  Speed: 10
  PanningSpeed: 0.5
  ScrollingSpeed: 0.5
Other:
  ObjectHighlightColor: [0, 1, 0]
Testing:
  ShowImGuiPrototypingWindow: false
Rendering:
  NearPlane: 0.0500000007
  FarPlane: 500