#pragma once

#ifdef FLOW_PLATFORM_WINDOWS

#define FLOW_MOUSE_LEFT			1
#define FLOW_MOUSE_RIGHT		2
#define FLOW_KEY_BREAK			3
#define FLOW_MOUSE_MIDDLE		4
#define FLOW_KEY_BACKSPACE		8
#define FLOW_KEY_TAB			9
#define FLOW_KEY_CLEAR			12
#define FLOW_KEY_RETURN			13
#define FLOW_KEY_SHIFT			16
#define FLOW_KEY_CONTROL		17
#define FLOW_KEY_ALT			18
#define FLOW_KEY_PAUSE			19
#define FLOW_KEY_CAPS_LOCK		20
#define FLOW_KEY_ESC			27
#define FLOW_KEY_SPACE			32
#define FLOW_KEY_PAGE_UP		33
#define FLOW_KEY_PAGE_DOWN		34
#define FLOW_KEY_END			35
#define FLOW_KEY_HOME			36
#define FLOW_KEY_ARROW_LEFT		37
#define FLOW_KEY_ARROW_RIGHT	39
#define FLOW_KEY_ARROW_UP		38
#define FLOW_KEY_ARROW_DOWN		40
#define FLOW_KEY_SELECT			41
#define FLOW_KEY_PRINT			42
#define FLOW_KEY_PRINT_SCREEN	44
#define FLOW_KEY_INSERT			45
#define FLOW_KEY_DELETE			46
#define FLOW_KEY_LEFT_WINDOWS	91
#define FLOW_KEY_RIGHT_WINDOWS	92
#define FLOW_KEY_NUMLOCK		144
#define FLOW_KEY_SCROLLLOCK		145
#define FLOW_KEY_LEFT_SHIFT		161
#define FLOW_KEY_RIGHT_SHIFT	162
#define FLOW_KEY_LEFT_CONTROL	163
#define FLOW_KEY_RIGHT_CONTROL	164
#define FLOW_KEY_LEFT_ALT		165
#define FLOW_KEY_RIGHT_ALT		166

#define FLOW_KEY_F1				112
#define FLOW_KEY_F2				113
#define FLOW_KEY_F3				114
#define FLOW_KEY_F4				115
#define FLOW_KEY_F5				116
#define FLOW_KEY_F6				117
#define FLOW_KEY_F7				118
#define FLOW_KEY_F8				119
#define FLOW_KEY_F9				120
#define FLOW_KEY_F10			121
#define FLOW_KEY_F11			122
#define FLOW_KEY_F12			123
#define FLOW_KEY_F13			124
#define FLOW_KEY_F14			125
#define FLOW_KEY_F15			126
#define FLOW_KEY_F16			127
#define FLOW_KEY_F17			128
#define FLOW_KEY_F18			129
#define FLOW_KEY_F19			130
#define FLOW_KEY_F20			131
#define FLOW_KEY_F21			132
#define FLOW_KEY_F22			133
#define FLOW_KEY_F23			134
#define FLOW_KEY_F24			135

#define FLOW_KEY_NUMPAD_0		96
#define FLOW_KEY_NUMPAD_1		97
#define FLOW_KEY_NUMPAD_2		98
#define FLOW_KEY_NUMPAD_3		99
#define FLOW_KEY_NUMPAD_4		100
#define FLOW_KEY_NUMPAD_5		101
#define FLOW_KEY_NUMPAD_6		102
#define FLOW_KEY_NUMPAD_7		103
#define FLOW_KEY_NUMPAD_8		104
#define FLOW_KEY_NUMPAD_9		105
#define FLOW_KEY_NUMPAD_MULTIPLY	106
#define FLOW_KEY_NUMPAD_ADD			107
#define FLOW_KEY_NUMPAD_ENTER		108
#define FLOW_KEY_NUMPAD_SUBTRACT	109
#define FLOW_KEY_NUMPAD_DIVIDE		110

#define FLOW_KEY_0				48
#define FLOW_KEY_1				49
#define FLOW_KEY_2				50
#define FLOW_KEY_3				51
#define FLOW_KEY_4				52
#define FLOW_KEY_5				53
#define FLOW_KEY_6				54
#define FLOW_KEY_7				55
#define FLOW_KEY_8				56
#define FLOW_KEY_9				57
#define FLOW_KEY_A				65
#define FLOW_KEY_B				66
#define FLOW_KEY_C				67
#define FLOW_KEY_D				68
#define FLOW_KEY_E				69
#define FLOW_KEY_F				70
#define FLOW_KEY_G				71
#define FLOW_KEY_H				72
#define FLOW_KEY_I				73
#define FLOW_KEY_J				74
#define FLOW_KEY_K				75
#define FLOW_KEY_L				76
#define FLOW_KEY_M				77
#define FLOW_KEY_N				78
#define FLOW_KEY_O				79
#define FLOW_KEY_P				80
#define FLOW_KEY_Q				81
#define FLOW_KEY_R				82
#define FLOW_KEY_S				83
#define FLOW_KEY_T				84
#define FLOW_KEY_U				85
#define FLOW_KEY_V				86
#define FLOW_KEY_W				87
#define FLOW_KEY_X				88
#define FLOW_KEY_Y				89
#define FLOW_KEY_Z				90

#endif